// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package argocdcomponent

import (
	"context"
	"reflect"

	"github.com/ediri/pulumi-argocd-component/sdk/go/argocdcomponent/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ArgoCDComponent deploys ArgoCD to a Kubernetes cluster using the official Helm chart.
//
// This component:
// - Creates an 'argocd' namespace
// - Deploys the ArgoCD Helm chart from oci://ghcr.io/argoproj/argo-helm/argo-cd
// - Auto-creates namespaces as needed
// - Uses the default Kubernetes provider
// - Waits for all resources to be ready before completing
//
// Note: Server-side apply is managed by the Kubernetes provider configuration.
// To enable it globally, configure the provider with enableServerSideApply: true.
type ArgoCDComponent struct {
	pulumi.ResourceState
}

// NewArgoCDComponent registers a new resource with the given unique name, arguments, and options.
func NewArgoCDComponent(ctx *pulumi.Context,
	name string, args *ArgoCDComponentArgs, opts ...pulumi.ResourceOption) (*ArgoCDComponent, error) {
	if args == nil {
		args = &ArgoCDComponentArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ArgoCDComponent
	err := ctx.RegisterRemoteComponentResource("argocd-component:index:ArgoCDComponent", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type argoCDComponentArgs struct {
}

// The set of arguments for constructing a ArgoCDComponent resource.
type ArgoCDComponentArgs struct {
}

func (ArgoCDComponentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*argoCDComponentArgs)(nil)).Elem()
}

type ArgoCDComponentInput interface {
	pulumi.Input

	ToArgoCDComponentOutput() ArgoCDComponentOutput
	ToArgoCDComponentOutputWithContext(ctx context.Context) ArgoCDComponentOutput
}

func (*ArgoCDComponent) ElementType() reflect.Type {
	return reflect.TypeOf((**ArgoCDComponent)(nil)).Elem()
}

func (i *ArgoCDComponent) ToArgoCDComponentOutput() ArgoCDComponentOutput {
	return i.ToArgoCDComponentOutputWithContext(context.Background())
}

func (i *ArgoCDComponent) ToArgoCDComponentOutputWithContext(ctx context.Context) ArgoCDComponentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ArgoCDComponentOutput)
}

type ArgoCDComponentOutput struct{ *pulumi.OutputState }

func (ArgoCDComponentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ArgoCDComponent)(nil)).Elem()
}

func (o ArgoCDComponentOutput) ToArgoCDComponentOutput() ArgoCDComponentOutput {
	return o
}

func (o ArgoCDComponentOutput) ToArgoCDComponentOutputWithContext(ctx context.Context) ArgoCDComponentOutput {
	return o
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ArgoCDComponentInput)(nil)).Elem(), &ArgoCDComponent{})
	pulumi.RegisterOutputType(ArgoCDComponentOutput{})
}
